version: 0.0
os: linux
files:
  - source: gameoflife-web-1.0-SNAPSHOT.war
    destination: /usr/share/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root

