version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - wget -P /opt https://services.gradle.org/distributions/gradle-6.2-all.zip
      - cd /opt
      - unzip gradle-6.2-all.zip
  build:
    commands:
      - echo Build started on `date`
      - cd /opt/gradle-6.2/bin
      - gradle build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - 'opt/gradle-6.2/bin/build/libs/*.jar'
    - 'appspec.yml'
    - 'scripts/before_install.sh'
    - 'scripts/after_install.sh'
    - 'scripts/start_server.sh'
    - 'scripts/stop_server.sh'
