name: ofbiz-demo

on: [push]
jobs: 
  build:
    name: ofbiz-demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifact
        uses: actions/upload-artifact@s3.console.aws.amazon.com
        with:
        # ofbiz-demo
        name: 
        # Directory containing files to upload
        path: https://s3.console.aws.amazon.com/s3/buckets/madhu-sample/?region=ap-southeast-1&tab=overview
